@host=localhost:8080

//ping pong test:
###
GET  http://{{host}}/ping
Host:{{host}}
###
//register urls
###
GET  http://{{host}}/register_urls
Host:{{host}}
###

//test url params:
###
GET  http://{{host}}/user/lenny
Host:{{host}}
###

// test httpBasicAuth with a value binding:
###
POST http://{{host}}/admin
Host:{{host}}
Authorization: Basic bGVubnk6bnVsbHBhc3M=
Content-Type: application/json

{

    "value": "You are now authorized"
}

// test post request with an amount binding..eg c to b daraja:
###
POST http://{{host}}/confirmation
Host:{{host}}
Content-Type: application/json

{
    "TransAmount": 1
}
###

// test post request with an amount binding..eg c to b daraja:
###
POST http://{{host}}/createuser
Host:{{host}}
Content-Type: application/json

{
    "username": "Lenny",
    "password": "oneGod",
    "role": 0
}
###

// test post request with an amount binding..eg c to b daraja:
###
GET http://{{host}}/users
Host:{{host}}

###
