@host=0fd4-41-84-130-206.ngrok-free.app

//ping pong test:
###
GET  https://{{host}}/ping
Host:{{host}}
###
//register urls
###
GET  https://{{host}}/register_urls
Host:{{host}}
###

//test url params:
###
GET  http://{{host}}/user/lenny
Host:{{host}}
###

// test httpBasicAuth with a value binding:
###
POST http://{{host}}/admin
Host:{{host}}
Authorization: Basic bGVubnk6bnVsbHBhc3M=
Content-Type: application/json

{

    "value": "You are now authorized"
}

// test post request with an amount binding..eg c to b daraja:
###
POST https://{{host}}/confirmation
Host:{{host}}
Content-Type: application/json

{
    "TransAmount": 1
}


###
